<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<meta name="description" content="Learn how to derive group sequential designs for time-to-event endpoints under both proportional and non-proportional hazards assumptions for randomized clinical trials.">
<title>Group Sequential Design Under Non-Proportional Hazards - 1&nbsp; Background</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./proportional-hazards.html" rel="next">
<link href="./preface.html" rel="prev">
<link href="./assets/favicon.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>
<meta property="og:title" content="Group Sequential Design Under Non-Proportional Hazards - 1&nbsp; Background">
<meta property="og:description" content="Learn how to derive group sequential designs for time-to-event endpoints under both proportional and non-proportional hazards assumptions for randomized clinical trials.">
<meta property="og:image" content="https://keaven.github.io/gsd-deming/assets/preview.jpg">
<meta property="og:site_name" content="Group Sequential Design Under Non-Proportional Hazards">
<meta name="twitter:title" content="Group Sequential Design Under Non-Proportional Hazards - 1&nbsp; Background">
<meta name="twitter:description" content="Learn how to derive group sequential designs for time-to-event endpoints under both proportional and non-proportional hazards assumptions for randomized clinical trials.">
<meta name="twitter:image" content="https://keaven.github.io/gsd-deming/assets/preview.jpg">
<meta name="twitter:card" content="summary_large_image">
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav"><div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./background.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Background</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Group Sequential Design Under Non-Proportional Hazards</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/keaven/gsd-deming" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
<li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
              <i class="bi bi-bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
</div>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./background.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Background</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./proportional-hazards.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Proportional hazards</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ahr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Average hazard ratio</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pkgs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Introduction to gsdmvn, gsDesign2, and simtrial</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./other-tests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Others tests</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fixed-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Fixed design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./wlr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Weighted logrank test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./wlr-boundary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Group sequential design boundary with weighted logrank test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./maxcombo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">MaxCombo test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./maxcombo-boundary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Group sequential design boundary with MaxCombo test</span></span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
</div>
</nav><div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#sec-nph" id="toc-sec-nph" class="nav-link active" data-scroll-target="#sec-nph"><span class="header-section-number">1.1</span> Non-proportional hazards</a>
  <ul class="collapse">
<li><a href="#sec-gsd" id="toc-sec-gsd" class="nav-link" data-scroll-target="#sec-gsd"><span class="header-section-number">1.1.1</span> Group sequential design</a></li>
  <li><a href="#z-process-and-b-process" id="toc-z-process-and-b-process" class="nav-link" data-scroll-target="#z-process-and-b-process"><span class="header-section-number">1.1.2</span> Z-process and B-process</a></li>
  <li><a href="#sec-EcfCf" id="toc-sec-EcfCf" class="nav-link" data-scroll-target="#sec-EcfCf"><span class="header-section-number">1.1.3</span> Canonical form</a></li>
  <li><a href="#sec-EcfEcf" id="toc-sec-EcfEcf" class="nav-link" data-scroll-target="#sec-EcfEcf"><span class="header-section-number">1.1.4</span> Extended canonical form</a></li>
  </ul>
</li>
  <li>
<a href="#sec-sf" id="toc-sec-sf" class="nav-link" data-scroll-target="#sec-sf"><span class="header-section-number">1.2</span> Spending function bounds</a>
  <ul class="collapse">
<li><a href="#haybittle-boundary" id="toc-haybittle-boundary" class="nav-link" data-scroll-target="#haybittle-boundary"><span class="header-section-number">1.2.1</span> Haybittle boundary</a></li>
  <li><a href="#wang-tsiatis-boundary" id="toc-wang-tsiatis-boundary" class="nav-link" data-scroll-target="#wang-tsiatis-boundary"><span class="header-section-number">1.2.2</span> Wang-Tsiatis boundary</a></li>
  <li><a href="#pocock-boundary" id="toc-pocock-boundary" class="nav-link" data-scroll-target="#pocock-boundary"><span class="header-section-number">1.2.3</span> Pocock boundary</a></li>
  <li><a href="#obrien-fleming-boundary" id="toc-obrien-fleming-boundary" class="nav-link" data-scroll-target="#obrien-fleming-boundary"><span class="header-section-number">1.2.4</span> O’Brien-Fleming boundary</a></li>
  </ul>
</li>
  <li><a href="#statistical-information-and-time" id="toc-statistical-information-and-time" class="nav-link" data-scroll-target="#statistical-information-and-time"><span class="header-section-number">1.3</span> Statistical information and time</a></li>
  </ul><div class="toc-actions"><ul><li><a href="https://github.com/keaven/gsd-deming/edit/main/background.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/keaven/gsd-deming/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/keaven/gsd-deming/blob/main/background.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">
<span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Background</span>
</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><section id="sec-nph" class="level2" data-number="1.1"><h2 data-number="1.1" class="anchored" data-anchor-id="sec-nph">
<span class="header-section-number">1.1</span> Non-proportional hazards</h2>
<p>Non-proportional hazards (NPH) are very common to see when there is a delayed effect. One example is given by KEYNOTE-040, which targets to cure recurrent head and neck squamous cell carcinoma. There are two arms, one is pembrolizumab, and the other is standard of care (SOC). The randomization ratio is 1:1 and the total sample size is 495. The primary endpoint is overall survival (OS) with 90% power for HR=0.7, 1-sided <span class="math inline">\(\alpha=0.025\)</span> (The detailed design can be referred to the <a href="https://ars.els-cdn.com/content/image/1-s2.0-S0140673618319998-mmc1.pdf">protocol</a>).</p>
<p>There are two interim analysis planned, one at 144 deaths (with information fraction as 0.42) and the other at 216 deaths (with information fraction as 0.64). The efficacy boundary is Hwang-Shih-DeCani (HSD) spending with <span class="math inline">\(\gamma=-4\)</span>, and the futility boundary is non-binding <span class="math inline">\(\beta\)</span>-spending HSD with <span class="math inline">\(\gamma = -16\)</span>. The final analysis finds there are 388 deaths, compared with 340 planned death. The 1-sided nominal <span class="math inline">\(p\)</span>-value for OS at the final analysis is 0.0161.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-keynote-040" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-keynote-040-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/ahr_slides_KEYNOTE040.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-keynote-040-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: KEYNOTE-040
</figcaption></figure>
</div>
</div>
</div>
<p>From the figure above, we can see there is a delay of the treatment effect.</p>
<p>The delayed effect is not just in oncology, it also lies in other TA. For example, in cholesterol lowering and mortality <span class="citation" data-cites="simva4s">(<a href="references.html#ref-simva4s" role="doc-biblioref">Miettinen et al. 1997</a>)</span>, there is also a delayed effect.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ssss" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-ssss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/ahr_slides_SSSS.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ssss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.2: Scandinavian Simvastatin Survival Study
</figcaption></figure>
</div>
</div>
</div>
<p>In addition to delayed effect, NPH also exists when there is a cross over of survival curves. For example, in KEYNOTE-061 (recurrent advanced gastric or gastro-oesophageal junction cancer), there is a cross over of the pembrolizumab arm and paclitaxel arm (see figure below). It is 1:1 randomization with 360 planned events (395 actual events) at the end of the trial in CPS <span class="math inline">\(\ge\)</span> 1 population. The first primary endpoints is OS in PD-L1 CPS <span class="math inline">\(\ge\)</span> 1. Its power is 91% for HR=0.67 with 1-sided <span class="math inline">\(\alpha=0.0215\)</span>. The secondary primary endpoints is PFS in PD-L1 CPS <span class="math inline">\(\ge\)</span> 1. (The detailed design can be found in the <a href="https://ars.els-cdn.com/content/image/1-s2.0-S0140673618312571-mmc1.pdf">protocol</a>.)</p>
<p>When it proceeded to final analysis, there are 326 deaths with 290 planned. One interim analysis is conducted with 240 events at information fraction of 0.83. During the group sequential design, the efficacy boundary is Hwang-Shih-DeCani (HSD) spending with <span class="math inline">\(\gamma=-4\)</span> and there is not a futility boundary. The 1-sided nominal <span class="math inline">\(p\)</span>-value for OS is 0.0421 (threshold: <span class="math inline">\(p\)</span>=0.0135). And <em>Post hoc</em> FH(<span class="math inline">\(\rho=1,\gamma=1\)</span>) is <span class="math inline">\(p\)</span>=0.0009.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-keynote-061" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-keynote-061-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="./images/ahr_slides_KEYNOTE061OS.PNG" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-keynote-061-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.3: KEYNOTE 061: Overall Survival in CPS 1.
</figcaption></figure>
</div>
</div>
</div>
<p>The above two examples motivate us to think about the following questions:</p>
<ul>
<li>The impact of (potentially) delayed treatment effect on trial design and analysis.</li>
<li>Test statistics used (logrank, weighted logrank test, and max-combo test)</li>
<li>Sample size vs.&nbsp;duration of follow-up</li>
<li>Timing of analyses</li>
<li>Futility bounds</li>
<li>Updating bounds</li>
<li>Multiplicity adjustments</li>
</ul>
<section id="sec-gsd" class="level3" data-number="1.1.1"><h3 data-number="1.1.1" class="anchored" data-anchor-id="sec-gsd">
<span class="header-section-number">1.1.1</span> Group sequential design</h3>
<p>In group sequential design, groups of observations are collected and repeatedly analyzed, while controlling error rates. While the group sequential design is ongoing, a stopping rule specifies when and why a trial might be halted at these points. This stopping rule usually consists of two components, a test statistic and a threshold. The threshold is usually decided by the spending functions, which we introduced in <a href="#sec-sf" class="quarto-xref"><span>Section 1.2</span></a>. And the test statistics are usually the Z-process and B-process, which are used to monitor the treatment effect under group sequential design. If a Z-process (B-process) cross the boundary, the trial is stopped.</p>
</section><section id="z-process-and-b-process" class="level3" data-number="1.1.2"><h3 data-number="1.1.2" class="anchored" data-anchor-id="z-process-and-b-process">
<span class="header-section-number">1.1.2</span> Z-process and B-process</h3>
<p>In this section, we will introduce the Z-process and B-process. Suppose in the group sequential design, there are totally <span class="math inline">\(K\)</span> looks. In the <span class="math inline">\(k\)</span>-th look, there are <span class="math inline">\(n_k\)</span> available observations. For notation simplicity, we denote the final number of available observations as <span class="math inline">\(N\)</span>, i.e., <span class="math inline">\(N \triangleq n_K\)</span>.</p>
<div id="def-Zprocess" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 1.1</strong></span> The Z-process is defined as the standardized treatment effect, i.e., <span id="eq-DefZprocess"><span class="math display">\[
  Z_{k}
  =
  \frac{\widehat\theta_k}{\sqrt{\hbox{Var}(\hat\theta_k)}},
\tag{1.1}\]</span></span> where <span class="math inline">\(k\)</span> is the index of the looks, and we assume there are totally <span class="math inline">\(K\)</span> number of looks, i.e., <span class="math inline">\(k = 1, 2, \ldots, K\)</span>. The numerator <span class="math inline">\(\widehat\theta_k\)</span> is the treatment effect estimated at the <span class="math inline">\(k\)</span>-th look.</p>
</div>
<p>For <span class="math inline">\(\widehat\theta_k\)</span>, its form depends on the outcome of the clinical trials. In clinical trials with continuous outcome <span class="math inline">\(X_1, X_2, \ldots \in \mathbb R\)</span>, the treatment effect estimated at the <span class="math inline">\(k\)</span>-th look is <span id="eq-DefThetaK"><span class="math display">\[
  \widehat{\theta}_k
  =
  \frac{\sum_{i=1}^{n_k} X_{i}}{n_k}\equiv \bar X_{k},
\tag{1.2}\]</span></span> where <span class="math inline">\(n_k\)</span> is the number of available observations at the <span class="math inline">\(k\)</span>-th look. In clinical trials with binary outcome <span class="math inline">\(X_1, X_2, \ldots \in \mathbb \{0, 1\}\)</span>, <span class="math inline">\(\widehat\theta_k\)</span> can be estimated the same as in <a href="#eq-DefThetaK" class="quarto-xref">Equation&nbsp;<span>1.2</span></a>. In clinical trials with survival outcome, <span class="math inline">\(\widehat\theta_k\)</span> would typically represent a Cox model coefficient representing the logarithm of the hazard ratio for experimental vs.&nbsp;control treatment. And <span class="math inline">\(n_k\)</span> would represent the planned number of events at <span class="math inline">\(k\)</span>-th look.</p>
<p>After discussing the Z-process, let us take a look at the B-process.</p>
<div id="def-Bprocess" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 1.2</strong></span> The B-process is defined as <span id="eq-DefBprocess"><span class="math display">\[
  B_{k} = \sqrt{t_k} Z_k,
\tag{1.3}\]</span></span> where <span class="math inline">\(Z_k\)</span> is defined in <a href="#def-Zprocess" class="quarto-xref">Definition&nbsp;<span>1.1</span></a> and <span class="math inline">\(t_k\)</span> is the information fraction at the <span class="math inline">\(k\)</span>-th look, i.e., <span class="math display">\[
  t_k = \mathcal I_k / \mathcal I_K,
\]</span> where <span class="math inline">\(\mathcal I_k\)</span> is the information at the <span class="math inline">\(k\)</span>-th look, defined as <span class="math display">\[
  \mathcal I_k \triangleq \frac{1}{\text{Var}(\widehat\theta_k)}.
\]</span></p>
</div>
<p>The information sequence plays an important role in the group sequential design. For example, in a clinical trial with continuous outcome <span class="math inline">\(X_1, X_2, \ldots \overset{i.i.d.}{\sim} N(\mu, \sigma^2)\)</span>, the information at the <span class="math inline">\(k\)</span>-th look is <span class="math inline">\(\mathcal I_k = n_k\)</span> with <span class="math inline">\(n_k\)</span> as the number of available observations at the <span class="math inline">\(k\)</span>-th look. The same logic applies to the binary outcome. Another example is a clinical trial with survival outcome. In this case, the information at the <span class="math inline">\(k\)</span>-th look is <span class="math inline">\(\mathcal I_k = n_k\)</span> with <span class="math inline">\(n_k\)</span> as the number of events at the <span class="math inline">\(k\)</span>-th look.</p>
</section><section id="sec-EcfCf" class="level3" data-number="1.1.3"><h3 data-number="1.1.3" class="anchored" data-anchor-id="sec-EcfCf">
<span class="header-section-number">1.1.3</span> Canonical form</h3>
<p>In the group sequential design, given the total <span class="math inline">\(K\)</span> look, there are sequences of Z-process and B-process, i.e., <span class="math inline">\(\{Z_k\}_{k = 1, \ldots, K}\)</span> and <span class="math inline">\(\{B_k\}_{k = 1, \ldots, K}\)</span>. The CF refers to the joint distribution of <span class="math inline">\(\{Z_k\}_{k = 1, \ldots, K}\)</span> and <span class="math inline">\(\{B_k\}_{k = 1, \ldots, K}\)</span>, including the distribution, the expectation mean, variance and covariance. Please note that this distribution is asymptotic, and the asymptotic conditions usually requires the sample size to be relative large. Properly speaking, both <span class="math inline">\(\{Z_k\}_{k = 1, \ldots, K}\)</span> and <span class="math inline">\(\{B_k\}_{k = 1, \ldots, K}\)</span> depends on the sample size, which can be re-denoted as <span class="math inline">\(\{ Z_{k,N} \}_{k = 1, \ldots, K}\)</span> and <span class="math inline">\(\{ B_{k, N} \}_{k = 1, \ldots, K}\)</span>. When the sample size is relatively large, we can get rid of the sample size, i.e., <span class="math display">\[
  Z_k = \lim\limits_{N \to \infty} Z_{k,N}.
\]</span> This asymptotic assumed throughout this book.</p>
<p>An important assumption of CF is <span class="math inline">\(E(\widehat\theta_k) = \theta\)</span>, where <span class="math inline">\(\theta\)</span> is a constant and <span class="math inline">\(\widehat\theta\)</span> is defined in <a href="#eq-DefThetaK" class="quarto-xref">Equation&nbsp;<span>1.2</span></a>.</p>
<div id="thm-ZprocessDistCF" class="theorem">
<p><span class="theorem-title"><strong>Theorem 1.1</strong></span> Suppose in a group sequential design, there are totally <span class="math inline">\(K\)</span> looks. At the <span class="math inline">\(k\)</span>-th look, there are <span class="math inline">\(n_k\)</span> available observations, i.e., <span class="math inline">\(\{X_i\}_{i = 1, \ldots, n_k}\)</span>. Assume that <span class="math inline">\(\text{Var}(X_i) = 1\)</span> for <span class="math inline">\(i = 1, 2, \ldots, N\)</span>. And denote <span class="math inline">\(\mathcal I_k \triangleq \frac{1}{\text{Var}(\widehat\theta(t_k))}\)</span> and <span class="math inline">\(E(\widehat\theta_k) = \theta\)</span>. The joint distribution of Z-process <span class="math inline">\(\{Z_k\}_{k = 1, \ldots, K}\)</span> is <span class="math display">\[
\left\{
\begin{array}{l}
  (Z_1, \ldots, Z_K) \text{ is multivariate normal} \\
  E(Z_k) =  \sqrt{\mathcal{I}_k}\theta \\
  \hbox{Var}(Z_k)  =  1 \\
  \text{Cov}(Z_i, Z_j)  =  \sqrt{t_i/t_j} \;\; \forall 1 \leq i \leq j \leq K
\end{array}
\right..
\]</span> where <span class="math inline">\(t_i = n_i / N\)</span> with <span class="math inline">\(N \triangleq n_K\)</span> as the final number of observations at the last look. If a statistics have the above distribution, we declare that it has the canonical joint distribution with information levels <span class="math inline">\(\{\mathcal I_1, \ldots, \mathcal I_K \}\)</span> for the parameter <span class="math inline">\(\theta\)</span>.</p>
</div>
<p>From the above theorem, we found that CF treats <span class="math inline">\(E(\widehat\theta)\)</span> as a constant, i.e., <span class="math inline">\(\theta\)</span>. Following the similar, we can also summarize the distribution of B-process.</p>
<div id="thm-BprocessDistCF" class="theorem">
<p><span class="theorem-title"><strong>Theorem 1.2</strong></span> Following the same setting of <a href="#thm-ZprocessDistCF" class="quarto-xref">Theorem&nbsp;<span>1.1</span></a>, the distribution of B-process is <span class="math display">\[
\left\{
\begin{array}{l}
  (B_1, \ldots, B_K) \text{ is multivariate normal} \\
  E(B_k) = \sqrt{t_{k}\mathcal{I}_k}\theta = t_k \sqrt{\mathcal{I}_K} \theta = \mathcal{I}_k \theta / \sqrt{\mathcal{I}_K} \\
  \hbox{Var}(B_k) = t_k \\
  \text{Cov}(B_i, B_j) = t_i \;\; \forall 1 \leq i \leq j \leq K
\end{array}
\right.,
\]</span> where <span class="math inline">\(t_i = n_i/N\)</span> with <span class="math inline">\(N \triangleq n_K\)</span> as the final number of observations at the last look.</p>
</div>
<p>It should be noted that the correlation of B-process is the same as the covariance of Z-process, i.e., <span class="math display">\[\begin{equation}
  Corr(B_i, B_j) = Cov(Z_i, Z_j) = \sqrt{t_i/t_j} \;\; \forall 1 \leq i \leq j \leq K.
\end{equation}\]</span> To learn this covariance/correlation better, let us take the continuous outcome as an example. Suppose there are <span class="math inline">\(K\)</span> looks in a clinical trial, and at the <span class="math inline">\(k\)</span>-th look, there are <span class="math inline">\(n_k\)</span> available observations with outcome <span class="math inline">\(\{ X_i \}_{i = 1, \ldots, n_k}\)</span>. In this example, we have <span class="math display">\[\begin{eqnarray}
  B_k
  &amp; = &amp;
  \sqrt{t_k} Z_k
  =
  \sqrt{\mathcal I_k / \mathcal I_K} \frac{\widehat\theta_k}{\sqrt{Var(\widehat\theta_k)}}
  =
  \mathcal I_k\sqrt{ 1 / \mathcal I_K}  \widehat\theta_k \\
  &amp; = &amp;
  \mathcal I_k\sqrt{ 1 / \mathcal I_K}  \frac{\sum_{i=1}^{n_k} X_i}{n_k}
  =
  \frac{\sum_{i=1}^{n_k} X_i}{\sqrt{I_K}}
  =
  \frac{\sum_{i=1}^{n_k} X_i}{\sqrt{N}}.
\end{eqnarray}\]</span> Given the above B-process, for any <span class="math inline">\(1 \leq i \leq j \leq K\)</span>, we have <span class="math display">\[
  B_j - B_i \sim N(\mathcal I_j \theta(t_j) - \mathcal I_i \theta(t_i), t_j - t_i)
\]</span> independent of <span class="math inline">\(B_1, B_2, \ldots, B_i\)</span>. So we have <span class="math display">\[\begin{eqnarray}
  Corr(B_i, B_j)
  &amp; = &amp;
  Cov(B_i, B_j) \bigg / \sqrt{Var(B_i) Var(B_j)} \\
  &amp; = &amp;
  t_i \bigg / \sqrt{t_i t_j} = \sqrt{t_i / t_j}   \\
  &amp; = &amp;
  Cov(Z_i, Z_j)
\end{eqnarray}\]</span></p>
</section><section id="sec-EcfEcf" class="level3" data-number="1.1.4"><h3 data-number="1.1.4" class="anchored" data-anchor-id="sec-EcfEcf">
<span class="header-section-number">1.1.4</span> Extended canonical form</h3>
<p>The main difference between extended canonical form (ECF) and canonical form (CF) is that, ECF treats <span class="math inline">\(E(\widehat\theta_k)\)</span> as a time-varying parameter, i.e., <span class="math inline">\(\theta(t_k)\)</span>. While CF treats it as a constant <span class="math inline">\(\theta\)</span>. So we summarize the joint distribution of Z-process and B-process under ECF as follows</p>
<div id="thm-ECF" class="theorem">
<p><span class="theorem-title"><strong>Theorem 1.3</strong></span> Suppose in a group sequential design, there are totally <span class="math inline">\(K\)</span> looks. At the <span class="math inline">\(k\)</span>-th look, there are <span class="math inline">\(n_k\)</span> available observations, i.e., <span class="math inline">\(\{X_i\}_{i = 1, \ldots, n_k}\)</span>. Assume that <span class="math inline">\(\text{Var}(X_i) = 1\)</span> for <span class="math inline">\(i = 1, 2, \ldots, N\)</span>. And denote <span class="math inline">\(\mathcal I_k \triangleq \frac{1}{\text{Var}(\widehat\theta(t_k))}\)</span> and <span class="math inline">\(E(\widehat\theta_k) = \theta(t_k)\)</span>. The joint distribution of Z-process <span class="math inline">\(\{Z_k\}_{k = 1, \ldots, K}\)</span> is <span class="math display">\[
\left\{
\begin{array}{l}
  (Z_1, \ldots, Z_K) \text{ is multivariate normal} \\
  E(Z_k) =  \sqrt{\mathcal{I}_k} \theta(t_k) \\
  \hbox{Var}(Z_k)  =  1 \\
  \text{Cov}(Z_i, Z_j)  =  \sqrt{t_i/t_j} \;\; \forall 1 \leq i \leq j \leq K
\end{array}
\right..
\]</span> And the joint distribution of B-process <span class="math inline">\(\{B_k\}_{k = 1, \ldots, K}\)</span> is <span class="math display">\[
\left\{
\begin{array}{l}
  (B_1, \ldots, B_K) \text{ is multivariate normal} \\
  E(B_k) = \sqrt{t_{k}\mathcal{I}_k}\theta(t_k) = t_k \sqrt{\mathcal{I}_K} \theta(t_k) = \mathcal{I}_k\theta(t_k)/\sqrt{\mathcal{I}_K}\\
  \hbox{Var}(B_k) = t_k \\
  \text{Cov}(B_i, B_j) = t_i \;\; \forall 1 \leq i \leq j \leq K
\end{array}
\right.,
\]</span> where <span class="math inline">\(t_i = n_i / N\)</span> with <span class="math inline">\(N \triangleq n_K\)</span> as the final number of observations at the last look. If a statistics have the above distribution, we declare that it has the canonical joint distribution with information levels <span class="math inline">\(\{\mathcal I_1, \ldots, \mathcal I_K \}\)</span> for the parameter <span class="math inline">\(\theta\)</span>.</p>
</div>
</section></section><section id="sec-sf" class="level2" data-number="1.2"><h2 data-number="1.2" class="anchored" data-anchor-id="sec-sf">
<span class="header-section-number">1.2</span> Spending function bounds</h2>
<p>In this section, we introduce the spending function bounds in group sequential design. We start with it definitions and categories. And then introduce three frequently used spending functions, (1) Haybittle boundary, (2) Pocock boundary and (3) O’Brien-Fleming boundary.</p>
<p>Suppose we have <span class="math inline">\(K\)</span> analyses conducted at information fraction of <span class="math inline">\(t_1, t_2, \ldots, t_k, \ldots, t_K\)</span>. We call the <span class="math inline">\(\{a_k, b_k \}_{k = 1,\ldots, K}\)</span> as the decision boundaries, if we reject <span class="math inline">\(H_0\)</span> when <span class="math inline">\(Z(t_k) &lt; a_k\)</span> or <span class="math inline">\(Z(t_k) &gt; b_k\)</span>. And we call <span class="math inline">\(\{b_k\}_{k=1,\ldots,K}\)</span> as the <em>efficiency boundary</em>, which are decided by the control of type I error, and <span class="math inline">\(\{a_k\}_{k=1,\ldots,K}\)</span> as the <em>futility boundary</em>, which are used to control boundary crossing probabilities.</p>
<p>For the calculation of boundaries, there are typically two methods. The first one is the so-called error spending approach, which specifies boundary crossing probabilities at each analysis. This is most commonly done with the error spending function approach <span class="citation" data-cites="LanDeMets">(<a href="references.html#ref-LanDeMets" role="doc-biblioref">Lan and DeMets 1983</a>)</span>. The second one is the so-called boundary family approach, which specifies how big boundary values should be relative to each other and adjust these relative values by a constant multiple to control overall error rates. The commonly applied boundary family include:</p>
<ul>
<li>Haybittle boundary <span class="citation" data-cites="haybittle1971repeated">(<a href="references.html#ref-haybittle1971repeated" role="doc-biblioref">Haybittle 1971</a>)</span>;</li>
<li>Wang-Tsiatis boundary <span class="citation" data-cites="wang1987approximately">(<a href="references.html#ref-wang1987approximately" role="doc-biblioref">Wang and Tsiatis 1987</a>)</span>:
<ul>
<li>Pocock boundary <span class="citation" data-cites="pocock1977group">(<a href="references.html#ref-pocock1977group" role="doc-biblioref">Pocock 1977</a>)</span>;</li>
<li>O’Brien and Fleming boundary <span class="citation" data-cites="o1979multiple">(<a href="references.html#ref-o1979multiple" role="doc-biblioref">O’Brien and Fleming 1979</a>)</span>.</li>
</ul>
</li>
</ul>
<p>In the remainder of this section, we will introduce the above spending functions one by one.</p>
<section id="haybittle-boundary" class="level3" data-number="1.2.1"><h3 data-number="1.2.1" class="anchored" data-anchor-id="haybittle-boundary">
<span class="header-section-number">1.2.1</span> Haybittle boundary</h3>
<p>The main idea of the Haybittle boundary is to set the interim Z-score boundary as 3 and the final boundary as 1.96, which is visualized in the figure below.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-bound-haybittle" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-bound-haybittle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/background_SF_Haybittle_boundary.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bound-haybittle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.4: Haybittle boundary
</figcaption></figure>
</div>
</div>
</div>
<p>The above Haybittle boundary has three modified versions.</p>
<p>The first modified version uses Bonferroni adjustment: for the first <span class="math inline">\(K-1\)</span> analyses, the significant <span class="math inline">\(p\)</span>-value is set as 0.001; and for the final analysis, the significant <span class="math inline">\(p\)</span>-value is set as <span class="math inline">\(0.05 - 0.01 \times (K-1)\)</span>. This modification helps to avoid type I error inflation. Besides, it does not require them to be equally spaced in terms of information and can be used regardless of the joint distribution of Z-score, i.e., <span class="math inline">\(Z(t_1),...,Z(t_k)\)</span>.</p>
<p>The second modified version sets the Z-score as 4 for the first half of the study and sets the Z-score boundary as 3 thereafter.</p>
<p>The third modified version requires crossing the boundary at two successive looks.</p>
<p>In summary, the Haybittle boundary uses a piecewise constant boundary, which makes it very easy to implement. But it is kind of conservative, and the selection of the constant boundary (e.g., 3 and 1.96) needs justifications.</p>
</section><section id="wang-tsiatis-boundary" class="level3" data-number="1.2.2"><h3 data-number="1.2.2" class="anchored" data-anchor-id="wang-tsiatis-boundary">
<span class="header-section-number">1.2.2</span> Wang-Tsiatis boundary</h3>
<p>For 2-sided testing, <span class="citation" data-cites="wang1987approximately">Wang and Tsiatis (<a href="references.html#ref-wang1987approximately" role="doc-biblioref">1987</a>)</span> defined the boundary function for the <span class="math inline">\(k\)</span>-th look as <span class="math display">\[
  \Gamma(\alpha, K, \Delta) k^{\Delta - 0.5},
\]</span> where <span class="math inline">\(\Gamma(\alpha, K, \Delta)\)</span> is a constant chosen so that the level of significance is equal to <span class="math inline">\(\alpha\)</span>.</p>
<p>With two selection of <span class="math inline">\(\Delta\)</span>, the Wang-Tsiatis boundary gives two special cases. When <span class="math inline">\(\Delta = 0.5\)</span>, it is the Pocock bounds. When <span class="math inline">\(\Delta = 0\)</span>, it is the O’Brien-Fleming bounds.</p>
</section><section id="pocock-boundary" class="level3" data-number="1.2.3"><h3 data-number="1.2.3" class="anchored" data-anchor-id="pocock-boundary">
<span class="header-section-number">1.2.3</span> Pocock boundary</h3>
<p>For 2-sided testing, the Pocock procedure rejects at the <span class="math inline">\(k\)</span>-th of <span class="math inline">\(K\)</span> looks if <span class="math display">\[
  |Z(k/K)| &gt; c_P(K),
\]</span> where <span class="math inline">\(c_P(K)\)</span> is fixed given the number of total looks <span class="math inline">\(K\)</span> and chosen such that <span class="math inline">\(\text{Pr}(\cup_{k=1}^{K} |Z(k/K)| &gt; c_P(K)) = \alpha\)</span>.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-bound-pocock" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-bound-pocock-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/background_SF_Pocock_boundary.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bound-pocock-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.5: Pocock boundary
</figcaption></figure>
</div>
</div>
</div>
<p>Here is an example of the Pocock boundary.</p>
<table class="table">
<colgroup>
<col style="width: 30%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">total number of looks(K)</th>
<th style="text-align: center;"><span class="math inline">\(\alpha = 0.01\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\alpha = 0.05\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\alpha = 0.1\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">2.576</td>
<td style="text-align: center;">1.960</td>
<td style="text-align: center;">1.645</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">2.772</td>
<td style="text-align: center;">2.178</td>
<td style="text-align: center;">1.875</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">2.939</td>
<td style="text-align: center;"><strong>2.361</strong></td>
<td style="text-align: center;">2.067</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">3.078</td>
<td style="text-align: center;">2.512</td>
<td style="text-align: center;">2.225</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\infty\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\infty\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\infty\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\infty\)</span></td>
</tr>
</tbody>
</table>
<p>We will reject <span class="math inline">\(H_0\)</span> if <span class="math inline">\(|Z(k/4)| &gt; 2.361\)</span> for <span class="math inline">\(k = 1,2,3,4\)</span> (final analysis).</p>
<p>In summary, the Pocock boundary is a special case of Wang-Tsiatis boundary (<span class="math inline">\(\Delta = 0.5\)</span>) and has constant Z-score boundaries, i.e., <span class="math inline">\(|Z(k/K)| &gt; c_P(K)\)</span>. And the constant boundary <span class="math inline">\(c_P(K)\)</span> is decided by the type I error rate and the total number of looks. Its main weakness is the high price for the end of the trial and the requirement of equally spaced looks.</p>
</section><section id="obrien-fleming-boundary" class="level3" data-number="1.2.4"><h3 data-number="1.2.4" class="anchored" data-anchor-id="obrien-fleming-boundary">
<span class="header-section-number">1.2.4</span> O’Brien-Fleming boundary</h3>
<p>O’Brien-Fleming boundary is very conservative at the beginning, which gives a relatively large boundary first. But it gives a nominal value close to the overall value of the design <span class="math inline">\(\approx 1.96\)</span> when two-side <span class="math inline">\(\alpha = 0.05\)</span> for the final stage. Its visualization can be found as follows.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-bound-obf" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-bound-obf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/background_SF_OBF_boundary.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bound-obf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.6: O’Brien-Fleming boundary
</figcaption></figure>
</div>
</div>
</div>
<p>Here is an example of the O’Brien-Fleming boundary.</p>
<table class="table">
<colgroup>
<col style="width: 30%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead><tr class="header">
<th style="text-align: center;">total number of looks(K)</th>
<th style="text-align: center;"><span class="math inline">\(\alpha = 0.01\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\alpha = 0.05\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\alpha = 0.1\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">2.576</td>
<td style="text-align: center;">1.960</td>
<td style="text-align: center;">1.645</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">2.580</td>
<td style="text-align: center;">1.977</td>
<td style="text-align: center;">1.678</td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;">2.609</td>
<td style="text-align: center;"><strong>2.024</strong></td>
<td style="text-align: center;">1.733</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: center;">2.648</td>
<td style="text-align: center;">2.072</td>
<td style="text-align: center;">1.786</td>
</tr>
<tr class="odd">
<td style="text-align: center;">16</td>
<td style="text-align: center;">2.684</td>
<td style="text-align: center;">2.114</td>
<td style="text-align: center;">1.830</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\infty\)</span></td>
<td style="text-align: center;">2.807</td>
<td style="text-align: center;">2.241</td>
<td style="text-align: center;">1.960</td>
</tr>
</tbody>
</table>
<p>Since the tabled value 2.024 is the flat B-value boundary. The B-value boundary can be easily transformed into decreasing Z-score boundary by <span class="math inline">\(Z(t) = B(t)/\sqrt{t}\)</span>:</p>
<ul>
<li><span class="math inline">\(2.024/\sqrt{1/4} = 4.05\)</span></li>
<li><span class="math inline">\(2.024/\sqrt{2/4} = 2.86\)</span></li>
<li><span class="math inline">\(2.024/\sqrt{3/4} = 2.34\)</span></li>
<li><span class="math inline">\(2.024/\sqrt{4/4} = 2.02\)</span></li>
</ul>
<p>In summary, the O’Brien-Fleming boundary designs a decreasing Z-score boundary, with large boundaries at the early stage but ~1.96 boundary when it approaches the final stage.</p>
<p>Although both the Pocock boundary and OBF boundary belong to the Wang-Tsiatis boundary’s family, there are two differences between them.</p>
<p>The first difference is, the Pocock boundary has flat Z-score boundaries, while the O’Brien-Fleming has decreasing Z-score boundary. Accordingly, the O’Brien-Fleming boundary makes it much more difficult to stop early than the Pocock boundary. However, the O’Brien-Fleming boundary extracts a much smaller price at the end.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-bound-pocock-obf" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-bound-pocock-obf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/background_SF_OF_P_t.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bound-pocock-obf-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.7: Pocock (circles) and O’Brien-Fleming (squares) z-score boundaries for four looks
</figcaption></figure>
</div>
</div>
</div>
<p>The second difference is, they have different performance in cumulative type I error rate (the probability of rejection at or before <span class="math inline">\(t_j\)</span>, i.e., <span class="math inline">\(\text{Pr}(\cup_{i=1}^j |Z(t_i)| &gt; c_i)\)</span>).</p>
<ul>
<li>The Pocock cumulative type I error rate increases sharply at first, but much less so toward the end.</li>
<li>The O’Brien-Fleming behaves in just the opposite way.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sf-cumulative-type-i" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-sf-cumulative-type-i-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/background_SF_cumType1_t.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sf-cumulative-type-i-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.8: Cumulative type I error rate used by the Pocock (circles) and O’Brien-Fleming (squares) procedures with four looks.
</figcaption></figure>
</div>
</div>
</div>
<p>In conclusion, we visualize the three spending functions in the following figure.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-sf-three" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure"><div aria-describedby="fig-sf-three-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/background_SF_ThreeBoundary.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sf-three-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.9: Three boundaries
</figcaption></figure>
</div>
</div>
</div>
</section></section><section id="statistical-information-and-time" class="level2" data-number="1.3"><h2 data-number="1.3" class="anchored" data-anchor-id="statistical-information-and-time">
<span class="header-section-number">1.3</span> Statistical information and time</h2>
<p>Statistical information and time is a key component in group sequential design. In this section, we introduce the statistical information under three different outcomes, (1) continuous outcome, (2) binary outcome and (3) survival outcome.</p>
<p>We start with the continuous outcome. Suppose in a <span class="math inline">\(T\)</span>-month trial, and the interim analysis is conducted after <span class="math inline">\(\tau\)</span> month with <span class="math inline">\(n\)</span> of <span class="math inline">\(N\)</span> planned observations evaluated in each arm. These <span class="math inline">\(n\)</span> available observation is denoted as <span class="math inline">\(\{X_i\}_{i = 1, \ldots, n}\)</span> for the control arm and <span class="math inline">\(\{Y_i\}_{i = 1, \ldots, n}\)</span> for the treatment arm. Thus, the treatment effect can be estimated as <span class="math display">\[
  \widehat\delta(\tau) = \frac{\sum_{i=1}^n (Y_i - X_i)}{n}.
\]</span> For <span class="math inline">\(Y_i - X_i\)</span>, we commonly assume that <span class="math inline">\(Y_i - X_i \overset{i.i.d.}{\sim} \text{Normal}(\mu, \sigma^2)\)</span> for any <span class="math inline">\(i = 1, \ldots, n\)</span>, with <span class="math inline">\(\mu = 0\)</span> under the null hypothesis and <span class="math inline">\(\mu \neq 0\)</span> under the alternative hypothesis.</p>
<p>The <em>information</em> at the <span class="math inline">\(\tau\)</span>-th month is <span class="math display">\[
  I(\tau) = 1/\text{Var}(\widehat\delta(\tau)) = n/\sigma^2.
\]</span> Accordingly, we define the <em>information fraction</em> as the ratio between interim information and final information, i.e., <span class="math display">\[
  t = I(\tau)/I(T)= \frac{n/\sigma^2}{N/\sigma^2} = \frac{n}{N}.
\]</span></p>
<p>For binary outcome, it follows the similar logic as that in continuous outcome. We commonly assume that <span class="math inline">\(Y_i - X_i \overset{i.i.d.}{\sim} \text{Bernoulli}(p)\)</span> for any <span class="math inline">\(i = 1, \ldots, n\)</span>, with <span class="math inline">\(p = 0.5\)</span> under the null hypothesis and <span class="math inline">\(p \neq 0.5\)</span> under the alternative hypothesis. The <em>information</em> at the <span class="math inline">\(\tau\)</span>-th month is <span class="math display">\[
  I(\tau) = 1/\text{Var}(\widehat\delta(\tau)) = \frac{n}{p(1-p)}.
\]</span> Accordingly, the <em>information fraction</em> is <span class="math display">\[
  t = I(\tau)/I(T)= \frac{\frac{n}{p(1-p)}}{\frac{N}{p(1-p)}} = \frac{n}{N}.
\]</span></p>
<p>For survival outcome, it is a little bit complicated. Suppose the interim analysis is conducted after <span class="math inline">\(\tau\)</span> month with <span class="math inline">\(d\)</span> of <span class="math inline">\(D\)</span> planned events evaluated in each arm. The treatment effect under survival outcome is usually measured by logrank test, i.e., <span class="math display">\[
  \widehat\delta(\tau)
  =
  \frac{\sum_{i=1}^d (O_i - E_i)}{\sum_{i = 1}^d V_i}
  \triangleq
  \frac{S(\tau)}{\sum_{i = 1}^d V_i}.
\]</span> Accordingly, the <em>information fraction</em> is <span class="math display">\[
\begin{array}{ccl}
  t
  &amp; = &amp; \text{Var}(S(\tau)) / \text{Var}(S(1)) \\
  &amp; = &amp; \text{Var}(\sum_{i =1}^{d} (O_i - E_i)) \bigg / \text{Var}(\sum_{i =1}^{D} (O_i - E_i)) \\
  &amp; = &amp; \sum_{i =1}^{d} \text{Var}(O_i - E_i) \bigg / \sum_{i =1}^{D} \text{Var}(O_i - E_i) \\
  &amp; = &amp; \sum_{i =1}^{d} E_i(1-E_i) \bigg / \sum_{i =1}^{D} E_i(1-E_i) \\
  &amp; \approx &amp; \sum_{i =1}^{d} 0.5(1-0.5) \bigg / \sum_{i =1}^{D} 0.5(1-0.5) \\
  &amp; = &amp; d/D.
\end{array}
\]</span></p>
<p>Comparing survival outcome and continuous/binary outcome, we found the information (fraction) of survival outcome is decided by the number of events, while it is decided by the number of available observations under continuous/binary outcome.</p>
<p>If there are multiple interim analysis at <span class="math inline">\(\tau_1\)</span>-th, <span class="math inline">\(\tau_2\)</span>-th, <span class="math inline">\(\ldots\)</span>, <span class="math inline">\(\tau_K\)</span>-th month, we get a sequence of information as <span class="math inline">\(I(\tau_1), I(\tau_2), \ldots, I(\tau_K)\)</span> and a sequence of information fraction <span class="math inline">\(t_1, t_2, \ldots, t_K\)</span>. Please note that the information sequence is sometimes simplified as <span class="math inline">\(I_1, I_2, \ldots, I_K\)</span> <span class="citation" data-cites="JTBook">(<a href="references.html#ref-JTBook" role="doc-biblioref">Jennison and Turnbull 2000</a>)</span>.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-haybittle1971repeated" class="csl-entry" role="listitem">
Haybittle, JL. 1971. <span>“Repeated Assessment of Results in Clinical Trials of Cancer Treatment.”</span> <em>The British Journal of Radiology</em> 44 (526): 793–97.
</div>
<div id="ref-JTBook" class="csl-entry" role="listitem">
Jennison, Christopher, and Bruce W. Turnbull. 2000. <em>Group Sequential Methods with Applications to Clinical Trials</em>. Boca Raton, FL: Chapman; Hall/CRC.
</div>
<div id="ref-LanDeMets" class="csl-entry" role="listitem">
Lan, K. K. G., and David L. DeMets. 1983. <span>“Discrete Sequential Boundaries for Clinical Trials.”</span> <em>Biometrika</em> 70: 659–63.
</div>
<div id="ref-simva4s" class="csl-entry" role="listitem">
Miettinen, Tatu A, Kalevi Pyörälä, Anders G Olsson, Thomas A Musliner, Thomas J Cook, Ole Faergeman, Kåre Berg, Terje Pedersen, John Kjekshus, and for the Scandinavian Simvastatin Study Group. 1997. <span>“Cholesterol-Lowering Therapy in Women and Elderly Patients with Myocardial Infarction or Angina Pectoris: Findings from the Scandinavian Simvastatin Survival Study (4S).”</span> <em>Circulation</em> 96 (12): 4211–18.
</div>
<div id="ref-o1979multiple" class="csl-entry" role="listitem">
O’Brien, Peter C, and Thomas R Fleming. 1979. <span>“A Multiple Testing Procedure for Clinical Trials.”</span> <em>Biometrics</em>, 549–56.
</div>
<div id="ref-pocock1977group" class="csl-entry" role="listitem">
Pocock, Stuart J. 1977. <span>“Group Sequential Methods in the Design and Analysis of Clinical Trials.”</span> <em>Biometrika</em> 64 (2): 191–99.
</div>
<div id="ref-wang1987approximately" class="csl-entry" role="listitem">
Wang, Samuel K, and Anastasios A Tsiatis. 1987. <span>“Approximately Optimal One-Parameter Boundaries for Group Sequential Trials.”</span> <em>Biometrics</em>, 193–99.
</div>
</div>
</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/keaven\.github\.io\/gsd-deming\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./preface.html" class="pagination-link" aria-label="Preface">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./proportional-hazards.html" class="pagination-link" aria-label="Proportional hazards">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Proportional hazards</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/keaven/gsd-deming/edit/main/background.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/keaven/gsd-deming/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/keaven/gsd-deming/blob/main/background.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div></div></footer></body></html>