# Welcome

## Outline



- 3:30: Introduction and background theory (30 minutes)

- 4:00: Proportional hazards applications with Shiny app (25 minutes)

- 4:25: Intro to non-proportional hazards (NPH; 5 minutes)

- 4:30: Software and piecewise model (15 min)

- 4:45: Average hazard ratio (AHR; 20 minutes)

- 5:05: Break (10 minutes)

- 5:15: NPH design with logrank test (25 minutes)

- 5:40: Weighted logrank and combination tests (40 minutes)

- 6:20 Summary and questions (10 minutes)

## Disclaimer

- All opinions expressed are those of the presenters and not
  Merck Sharp & Dohme Corp., a subsidiary of Merck & Co., Inc., Kenilworth, NJ, USA.

- Some slides need to be scrolled down to see the full content.

## Software

For minimum effort and maximum benefit, you will probably at least want to use the Shiny interface for the **gsDesign** R package at <https://rinpharma.shinyapps.io/gsdesign/>.
This is also available at <https://gsdesign.shinyapps.io/prod/>, but this site is only licensed for a small number of simultaneous users.

## Course resources

- Book at <https://keaven.github.io/gsd-deming/>
    - Instructions there to install software, download repository at <https://github.com/keaven/gsd-deming>
    - Directories there we will use:
        - `data/`: contains design files for examples; also simulation results
        - `vignettes/`: reports produced by Shiny app to summarize designs
        - `simulation/`: R code and simulation data for the last part of course
